### ISSUE TITLE
is_photo_already_uploaded: file already loaded without Set

### ISSUE THREAD

**Issue by oPromessa** [oPromessa/flickr-uploader#29]
Address scenarios:
### B) checksum, title, empty setName,       Count=1  THEN EXISTS, ASSIGN SET

One has to pay attention for same pics (with same checksum) on different Albums... while being loaded and not assigned to a Set, one cannot assume we can assign it a Set!

**Comment by oPromessa** [comment]
One option can be to include in the pic tags, aside from the CHECKSUM, the Album also.
- with Title, Checksum and Album your bound to find the appropriate pic.
- Need to consider updating the Album tag on the pics already loaded!

**Comment by ze6killer** [comment]
A tag with the album name sounds good indeed.
