### ISSUE TITLE
Several Clarifications on how upload/sync works | non-ascii characters | MAC OSX crontab issue

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#31]
Hi,

First off: thanks for the good work and while I'm at it, happy new year and a good health to you :)

I just wanted to report an issue, which might concern foreigners more as english speakers: the code currently doesn't seem to support non-ascii characters, which means any picture or folder with accents, for exemple, can't be handled.
FOr instance, right after your comment `_# Now everything should be in Unicode_` I get a crash on the line `if excluded_dir in os.path.dirname(filename)`

This probably won't make your top-priority list, but if you could fild some time to look into it at some point, it would be a game-changer for me (like: not having to parse & rename 60GB worth of pictures and folders :)

Hope this helps.
Keep up the good work.

Regards,
Ze

**Comment by oPromessa** [comment]
Thanks for your comments!

I'm using it with international characters. That's a *must* for me for both folder and file names.
Let me know which python version you're using (2.7 or 3.6) which handles unicode differently.

I also use international (western) characters and I had to force the following on the Task Scheduler of Synology... Although it states en_US with the utf8 added to it allows mine to work.
```
export LC_ALL=en_US.utf8
export LANG=en_US.utf8
```
I've attached [upload.cron](https://github.com/oPromessa/flickr-uploader/blob/2.6.5/uploadr.cron) file that I use for Task Scheduler.

If you can setup the ERROR_LEVEL to DEBUG on [upload.cron](https://github.com/oPromessa/flickr-uploader/blob/2.6.5/uploadr.ini) and drop me the traces (uplaodr.py -v > uploard.log 2>&1) and I can try to check it out. Make sure you delete from the log file the "key", "secret" and "username" information about your flickr account.

If it fails where you indicate... are you setting up EXCLUDED_FOLDERS in uploadr.ini?

Thanks, oPromessa

**Comment by ze6killer** [comment]
Hi,

Thx for your fast reply!

First off, I have to say there's something I might be doing wrong because the scheduling part is not clear for me.
I tried:
- launching the .py script from ssh
- from Task Scheduler with `
export PYTHONPATH=$PYTHONPATH:~/apps/Python/lib/python2.7/site-packages
/bin/python ~/apps/Python/flickr-uploader-oPromessa/uploadr2.py --dry-run
` (without the PATH it didn't work)
- then after your message I edited crontab to add `0  *  *  *  * /full/path/to/uploadr.cron`
- and then `0  *  *  *  * /full/path/to/uploadr.cron > /dev/null 2>&1` (I changed the 0 so that it should fire a few minutes later according to my computer's clock)
- and finally I launched uploadr.cron manually via ssh.

I actually don't understand why I have crontab/taskscheduler/SLEEP_TIME. All these 3 things seem redundant to me.


This being said, here are my files. And to answer your question: I didn't modify the EXCLUDED_FOLDERS list yet.

[uploadr.ini.txt](https://github.com/oPromessa/flickr-uploader/files/1648102/uploadr.ini.txt)
[uploadr.err.txt](https://github.com/oPromessa/flickr-uploader/files/1648098/uploadr.err.txt)
[uploadr.out.txt](https://github.com/oPromessa/flickr-uploader/files/1648099/uploadr.out.txt)
[uploadr.cron.txt](https://github.com/oPromessa/flickr-uploader/files/1648106/uploadr.cron.txt)

Kind Regards, Ze

**Comment by oPromessa** [comment]
To your launch questions... I guess the instructions may not be fully correct. Sorry for that.
- I prefer to use the Task Scheduler from Synology. I adjust the run schedule settings, the email notifications and under "Run Command" I include:
`/full/path/to/uploadr.cron`
- Do not use crontab directly. Having Task Scheduler replaces crontab. Recommend not to use it. My bad the notes are not clear [They were also intended for peopple with regular Linux systems and not Synology systems.] *Will make it clear on the instructions*.
- The SLEEP_TIME is *only* used if you launch from the ssh with the -d (--daemon) option. Other than that it is ignored. My recommendation is again to go with Task Scheduler and no need to use the -d option and the SLEEP_TIME from uploadr.ini file is ignored alltogether.

The unicode/non-ascii characters is on FILES_DIR definition. Will check why it is failing and come back to you with a fix...

Thanks, oPromessa

**Comment by oPromessa** [comment]
Fixed on Version [2.6.6](https://github.com/oPromessa/flickr-uploader/tree/2.6.6).

Please try it out and let me know.

**Comment by ze6killer** [comment]
Hi,

1) Thx for your explanations. Very clear.
2) Fix seems to work as far as I could tell.
3) Thanks :)

4) A few things which are still unclear to me, maybe you can include this in the Readme sometime. No emergency though, I'm glad the script seems to be working fine now :)

- my understanding is that this is a sync script, which means when I later delete a pic from a synced folder, it will get deleted from Flickr
- what about previously existing folders (they didn't seem to get deleted)
- what about when I sync a folder with the same name of a previously existing folder? (you mention 
> getting existing sets from Flickr is managed also

- what about when I run the script on `~/pictures/parent_folder/folder_A` and then later on `~/pictures/parentfolder`  will the script recongize the folder_A within parentfolder as being the one it uploaded before becaues its content will have matching checksums?
- I thought I read a mention of checksum as a way to detect file modification: what about the same file in 2 different folders, is it then upoad each time (in a set with the folder name) or only once? 

Kind Regards, Ze

**Comment by oPromessa** [comment]
Excellent news. Thanks for the feedback!

## 1st a clarification: 
- the standard mode of operation should be to sync always the same main folder structure with all your subfolder/pics.
- syncing different folders on each run *does work* and uploads new pics; but uploadr was not originally designed for that. 
   - What happens to previously loaded pics depends if they still exist and Uploadr can still find them (depending if FILES_DIR was set as an absolute folder or relative folder path)
      - File to upload: /home/user/media/2014/05/05/photo.jpg
      - FULL_SET_NAME:
         - False: 05
         - True: 2014/05/05
   - Uploadr saves the (full or relative depending on FILES_DIR) path name for the pics loaded. So, event though you provide a new origin folder, if the previously loaded pics still exist on their original locations, they are not deleted. If they are deleted from such original location or uploadr has no access to them, then they will be deleted from flickr.
    - If using relative FILES_DIR and two files exist on the same subfolder, it will not be re-uploaded.

So, in a nutshell, too many issues if you play around changing the FILES_DIR location.

### Sample file structure
If you have the following folders and pics  (the name of the flickr setnames/Albums depends on the uploadr.ini file setting FULL_SET_NAME, but I normally use it as False):
```
/home/user/media/pic00.jpg
/home/user/media/Album1/pic01.jpg
/home/user/media/Album2/pic02.jpg
/home/user/media/Album3/pic03.jpg
/home/user/media/folder/Album4/pic04.jpg
/home/user/media/folder/Album4/Sub/pic041.jpg
/home/user/media/newfolder/Album4/pic042.jpg
/home/user/media/folderAlbum5/pic01.jpg

```

And you setup FILES_DIR
```
FILES_DIR=/home/user/media
```
You should get the following:

| FilePathName | SetName/Album Name (with FULL_SET_NAME=False) | SetName/Album Name (with FULL_SET_NAME=True) | Pic | Remarks | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| /home/user/media/pic00.jpg | media | . | pic00 | |
| /home/user/media/Album1/pic01.jpg | Album1 |  Album1 | pic01 | |
| /home/user/media/Album2/pic02.jpg | Album2 |  Album2 | pic02 | |
| /home/user/media/Album3/pic03.jpg | Album3 |  Album3 | pic03 | |
| /home/user/media/folder/Album4/pic04.jpg | Album4 | folder/Album4 | pic04 | |
| /home/user/media/folder/Album4/Sub/pic041.jpg | Sub  | folder/Album4/Sub  | pic041 | |
| /home/user/media/newfolder/Album4/pic042.jpg | Album4 | newfolder/Album4 | pic042 | |
| /home/user/media/Album5/pic01.jpg | Album5 |  Album5 | pic01 | It's the same pic as in Album01 but it will be loaded twice as it belongs to a different Album |

## Questions & Answers
*Remark*: I'm assuming in between each run you keep the contents of the flickrdb control database and do not remove it.
1. "my understanding is that this is a sync script, which means when I later delete a pic from a synced folder, it will get deleted from Flickr"
   - Yes a locally filed
1. "what about previously existing folders (they didn't seem to get deleted)"
   - If all files from a folder (and corresponding Album on flickr) are deleted, then the actual Album will be also eliminated. Again, if you do not chnage the FILES_DIR in between runs.
1. what about when I sync a folder with the same name of a previously existing folder? (you mention
getting existing sets from Flickr is managed also
   - hmmm... if you mean "sync a folder" via setting FILES_DIR... it would depend if you use full or relative pathname on FILES_DIR. Check the section "Clarification" above. It will delete the files he cannot find locally.
   - hmmm... if you mean two subfolders with the same name, to which Set/Album will be added depends on the setting FULL_SET_NAME. Check the section "Clarification" above for example pic042.
1. what about when I run the script on ~/pictures/parent_folder/folder_A and then later on ~/pictures/parentfolder will the script recongize the folder_A within parentfolder as being the one it uploaded before becaues its content will have matching checksums?
   - Again it depends on FULL_SET_NAME setting and FILE_DIR being an absolute or relative path and the match is initially done by full pathname + filename. So, in your example ~/pictures will expand to a full path so it would recognize the same files and not upload them again.
1. I thought I read a mention of checksum as a way to detect file modification: what about the same file in 2 different folders, is it then upoad each time (in a set with the folder name) or only once?
   - same file on two folders loads up twice. Check example above with Album5/pic02.jpg

**Comment by ze6killer** [comment]
Hello,

Thanks for all the details. I hope it will also be usefull for some other people, because your answer was very detailed!
I'm sorry for all the questions. I know I always ask too many of them :)

I'll try to stop after these two:

- > though you provide a new origin folder, if the previously loaded pics [...] then they will be deleted from flickr.

So this kind of means that, once a folder "xxx" has been used as origin, even if it's not a subfolder of the new origin "yyy" , the script, by parsing the database each time, will keep track of this folder "xxx"'s content and delete photos that disappear (but not add new ones). Did I understand right?

- > what about when I sync a folder with the same name of a previously existing folder?

Here I meant: what if I already have a set on Flickr named "xxx" and one of my subfolders is called "xxx" and I'm in FULL_SET_NAME=False?
My guess is that the script will merge content of the "xxx" folder with the existing set on Flickr, but that the pictures which were already in the "xxx" flickr set will not be copied to the database so they will be 'invisible' for the script.

I'm asking this because most of my folders are alreay on Flickr in sets so I guess the script will upload the pictures to those sets while ignoring the pictures already there -> all pics will be in double.
Still, if this happens I can simply sort pictures by upload date on flickr and delete all the old ones I guess :)

I would have tested instead of asking but for some reason Flickr seems extremely sloooooooow for me today (>30sec to load one pic.. although my connection quite fast with other services)

Sorry again for being so curious and my sincere thanks for helping me out and also providing this script in the first place!

Kind Regards, Ze

**Comment by oPromessa** [comment]
- 1st question
   - yes, you got it! although I think it will also not delete from flickr.
- 2nd question
   - yes, you got it.
   - "pics would be double"... hmmm, yup as the tool searchs for pics with tag checksum, and the ones you've had earlier do not have such a tag.
   - you can sort or search for pics with tag "auto-upload" (or whatever tag you actually configure on uploadr.ini for the pics loaded via uploadr)

**Comment by ze6killer** [comment]
Ok, thanks for taking the time to clarify all this for me.

Kind Regards,
Ze

**Comment by ze6killer** [comment]
Hello,

Current status: 
I had started with a single folder (with an accent if you remember) with only one pic inside, which got uploaded to the album as expected.
I then moved on to a "2017" folder with some 20 sub-folders within. Some pics were uploaded, but none seem to have been put within an album.

Maybe it's because the pics were already in flickr from a previous manual upload with same name/size and target folder but no checksum tag of course
or because the script crashed at some point: Task Manager indicates "error" as current state with
`
Start
[2018-02-03 16:04:06] Start ----
` as the output and the uploadr.out's last line read:

`[32m[1638][2018.02.03 17:01:52]:[488][0m[PRINT   ]:[uploadr] Checking file:[/var/services`

Still, even if it crashed, I'd have thought that the photos would have been alocated to the albums in the same time as they were uploaded..
I'll try running the script again and post an update.

**Comment by oPromessa** [comment]
Sorry for the delay. 

Yes let me know the results of your tests. 

Would love to see the logs/traces from your tests... as you sent me earlier. 

Thanks. oPromessa

**Comment by ze6killer** [comment]
Hello,

Don't mention the delay please, I'm already grateful you are looking into this!

So the script is launched on a daily basis.
Last run was this morning at 1am. Task scheduler reports: `interrupted (126)`
standard output/error: `sh: line 2: /root/apps/Python/flickr-uploader-oPromessa/uploadr.cron: Permission denied`


Output files created around 6am (according to Mas OS Finder):
[uploadr.err.txt](https://github.com/oPromessa/flickr-uploader/files/1701040/uploadr.err.txt)
[uploadr.out.txt](https://github.com/oPromessa/flickr-uploader/files/1701041/uploadr.out.txt)

I just checked again on Flickr: last file uploaded on Feb 3rd (3 days ago)
The file still isn't part of any set/album (I didn't check for ALL the files...)

So from what you wrote I understand that, since for some reason the script crashed during my first session, the final step during which the photos are put in albums was skipped.
During the next sessions, since the photos were not uploaded again (same checksum) they were not put into albums either.
Could this be it?

Can you understand from the 2 uploaded files where the 'permission denied' might have come from?
I haven't change any rights, the script is run under my main user, who has the same rights as the admin (as far as I know)
The only modification I made recently was to created 2 new users, but I didn't even open the task scheduler window these last 3 days...  oO


Good luck sherlock!  :)

Kind Regards,
Ze

...

**Comment by oPromessa** [comment]
Hello @ze6killer . We have two issues...

1. The execution permission of "uploadr.cron" is not correctly set. Don't know how it was able to run previously or if you ran it manually. Any how, to fix it you need to add the execution bit "x" to "uploadrd.cron" with the "chmod +x uploadr.cron" command on a Terminal Window.
- so launch a Terminal Window on Mac OS
- go to the folder where uploadr.cron is (adjust as necessary)
`$ cd /var/services/homes/pTim/apps/Python/flickr-uploader-oPromessa`
- check if the the "x" bit is set. It probably is *NOT* and shows as a "-" on  the characters sequence "-rw-r--r--"
`$ ls uploadr.cron`
`-rw-r--r-- 1 ruler users 1159 Jan 20 22:34 uploadr.cron`
- add the "x" execution bit...
`$ chmod +x uploadr.cron`
- finally check again if the "x" now shows up on every 3 characters (position 4, 7 and 10) on the characters sequence "-rwxr-xr-x"
`$ ls uploadr.cron`
`-rwxr-xr-x 1 ruler users 1159 Jan 20 22:34 uploadr.cron`

2. Once you fix this one... I see some "uploadr.py" stops for no special reason... 
- and thus no assignment to sets is done (the 1st runs with 1 and 3 files worked perfectly and such initial pics loaded *should* are assigned to an Album). 
- to help me troubleshoot... please edit "uploadr.ini" and change the last line "LOGGING_LEVEL = 10" instead of "LOGGING_LEVEL = 40" to generate *more output details to help me out track the issue.* 
- again, remove the key and secret private related information from the uploadr.out and uploadrd.err  before sending them out to me.

**Comment by ze6killer** [comment]
Yeah.. right.. so it's not that easy I'm afraid (wait.. what? Did it sound easy in the first place?)
So I got this:
```
pTim@Elephant:~/apps/Python/flickr-uploader-oPromessa$ ls -l uploadr.cron 
-rwxrwxrwx+ 1 pTim users 1006 Jan 21 14:46 uploadr.cron
pTim@Elephant:~/apps/Python/flickr-uploader-oPromessa$ ls -le uploadr.cron 
-rwxrwxrwx+ 1 pTim users 1006 Jan 21 14:46 uploadr.cron
	 [0] user:pTim:allow:rwxpdDaARWcCo:---- (level: 4)
	 [1] group:administrators:allow:rwxpdDaARWc--:---- (level: 5)
	 [2] user:Lodie:allow:rwxpdDaARWc--:---- (level: 5)
	 [3] everyone::allow:--x----------:---- (level: 5)
	 [4] user:pTim:allow:rwxpdDaARWcCo:---- (level: 5)
```
I'm not sure how the scheduler runs the script, but everybody seems to have user permissions, right?
(I won't try to understand why user:pTim appears 2 times, this is not the current topic)

Anyway, as you had guessed, I had run it a few times manually.
So I did it again and here are the outputs.
Actually I removed most of the subfolders because I suspected that the interruption was due to the whole process being too long.
With only 3GB of data left to upload it looks like it worked all right; I checked on Flickr and the files seem to be in albums.

In this case I "only" need to solve the permissions issue for it to run automatically :>

[uploadr.out.txt](https://github.com/oPromessa/flickr-uploader/files/1708653/uploadr.out.txt)

[uploadr.err.txt](https://github.com/oPromessa/flickr-uploader/files/1708677/uploadr.err.txt)

**Comment by oPromessa** [comment]
Good to know.

1. So... we still have to figure why it "stops" with huge files list (3GB).
1. On the "Permission denied"
   1. Do you get any mail with the result of the crontab? On the Terminal window you can run "mail" to check for any email which could bring any indications on errors.
   1. Please run "crontab -l" to confirm how it is set.
   1. Side note: MAC OSX is moving away from crontab... but in my high Sierra version I still have crfontab entries working.

**Comment by oPromessa** [comment]
- One last note... try to use [V2.6.7](https://github.com/oPromessa/flickr-uploader/releases/tag/2.6.7)

**Comment by ze6killer** [comment]
Hello,

Thanks as always for your feedback.
I will run v2.6.7

Regarding crontab I'm not sure:
1) You talk about the mac running things but I'm only using my mac to access the NAS, I don't run the scripts from there. When I launch them manually it's from the tasks scheduler
2) You mean I should try "crontab -l" but on my mac it returns nothing and while connected via ssh to the nas, crontab is not recognized.

As for the interruptions can it be that my daily start_shutdown of the NAS is what interrupts the upload process if uploading in bulk talkes too many hours?

Regards,
Z

**Comment by oPromessa** [comment]
- I thought you were using a MAC. Now I understand you're running off the NAS. Great! Yes, "crontab -l" does not work on the Unix NAS version. **Point closed!**
- Yes, you need to run it manually the first time and follow the instructions to connect with flickr for authentication (copy and pasting the presented URL into a browser and getting back the NNNN-NNNN-*NOT# code). But that's done already so no problem there.  **Point closed!**
- On the interruptions I did notice they were around the exact hour.. so possibly related with your daily reboot. Myself I let the NAS run forever (model 415+) and only reboot on updates... or when I have some issues. **Point clear... closed???**
- I understand some of your files are quite large so it **does** take a while to load. Suggestions:
   - disable the NAS daily reboot for now...
   - without going **overboard** so as not to overload your NAS server (you can check how well is performing with the "top" command) you can change the "10" to "30" or "40" (again my 415+ survived a setting of "40") to allow up to 30 or 40 simultaneous upload (hope you have good upload bandwidth!) to go faster. Edit "uploadr.cron" file and change the value of the "-p" parameter:
`python2.7 $FOLDER/uploadr.py -v -b -p 10 >>$FOLDER/uploadr.out 2>>$FOLDER/uploadr.err`
to
`python2.7 $FOLDER/uploadr.py -v -b -p 30 >>$FOLDER/uploadr.out 2>>$FOLDER/uploadr.err`

Good luck!

**Comment by ze6killer** [comment]
Ok, but there remains the problem that the task seems only to perform when I launch it myself from the task scheduler. When scheduled it stops and returns the access denied message.

**Comment by oPromessa** [comment]
Yup.

- The email you get from the NAS (I've copied your output here below) indicates "uploadr.cron" somehow ran correctly this past Saturday. Now I don't know if via "Synology Control Panel Task Scheduler" or via "crontab" or if you launched it mannually.
- Moreover I guess we're having some conflict of Task Scheduler and crontab.

Anyhow, let's go back to basics... ;)

- Let's avoid fulling around with crontab on Synology NAS and make sure we only use "Synology Control Panel Task Scheduler" 
   - based on my remarks [above](https://github.com/oPromessa/flickr-uploader/issues/31#issuecomment-359168297)
   - as well as the instructions found under section [On Synology systems, run with Task Scheduler (Synology/Control Panel)](https://github.com/oPromessa/flickr-uploader/blob/2.6.7/README.md#on-synology-systems-run-with-task-scheduler-synologycontrol-panel) of the README.md
   - The [Synology Help Article on Task Scheduler](https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/system_taskscheduler) may also be helpful.
```
Tâche : Flickr Upload
Heure de début : Sat, 10 Feb 2018 01:34:54 GMT
Heure d’arrêt : Sat, 10 Feb 2018 01:35:02 GMT
État actuel : 0
Sortie standard/erreur :
Start
[2018-02-10 01:34:55] Start ----
Result
0
End
[2018-02-10 01:35:02] End ----
---------
```

**Comment by ze6killer** [comment]
Hello,

1) /etc/crontab clean (didn't display any task added by me)
But I noticed that all tasks were for **root** even though in my Task Scheduler I set **pTim** as user under the **general** tab. I'm just mentioning it because I thought it might play a role for relative paths (I'm using full path in the **parameters** tab but what about the scripts?)

2) I deleted the .err and .out files

3) from now on, I only run the script by setting the task scheduler time 2min from the current time

Latest result by mail:
```
Tâche : Flickr Upload
Heure de début : Sun, 11 Feb 2018 05:43:02 GMT
Heure d’arrêt : Sun, 11 Feb 2018 05:43:06 GMT
État actuel : 0
Sortie standard/erreur :
Start
[2018-02-11 05:43:03] Start ----
Result
0
End
[2018-02-11 05:43:06] End ----
---------
---------
---------
Further output on file: /volume1/homes/pTim/apps/Python/flickr-uploader-oPromessa/uploadr.out
---------
```

uploadr.out -> empty
uploadr.err ->
```
Traceback (most recent call last):
  File "/volume1/homes/pTim/apps/Python/flickr-uploader-oPromessa/uploadr.py", line 181, in <module>
    import flickrapi
ImportError: No module named flickrapi

```
I've been playing around with PATH and stuff for 90min now but couldn't get to it to work past this.

**Comment by oPromessa** [comment]
Hurrah!!! Super!!!

- My tasks are set to run as "root"... so that play a role on permissions and PATH variable. The PYTHONPATH **does** have to be added to the "uploadr.cron" file.
- Whenever you need to launch the Task (outside of their schedule) you can run it manually from "Task Scheduler"
- For future debugging and if necessary, you could include the command "env" on the " uploaded.cron"  just before you run "uploadr.py" to print all the environment variables values.

Thanks for your help, patience and perseverance.

oPromessa
