### ISSUE TITLE
EOF when reading a line

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#40]
Hey,

I don't know if you'll love me for helping debug your script or if you'll hate me for constantly asking for help. Hopefully rather the first option :)

So I ran the script successfully over the last few days and 2 day ago I started seing some 'EOF when reading a line' in my mail reports. This happened more or less when 100% of my files had been uploaded, so maybe it's linked to the fact that there is no new file to upload (or not at all, I'm just giving as much info as I can)

I didn't try adding 1 new pic and running it again but I could if you think it might help.

Also a few days ago I launched the script by clicking on "Execute" on the Scheduler interface rather than letting it launch at the specified time. I just wanted to mention it since it seemed to make a difference when I had my PATH problems.

Here are the logs with modified keys and tokens (if I didn't miss any ^^):
[uploadr.err.txt](https://github.com/oPromessa/flickr-uploader/files/1741510/uploadr.err.txt)
[uploadr.out.txt](https://github.com/oPromessa/flickr-uploader/files/1741511/uploadr.out.txt)

Hope this helps.

Kind Regards,
Ze

**Comment by oPromessa** [comment]
No... definetely thank you for helping debug and also for your message from a few days ago. Appreciate it.

- What is happening is that for some reason the Flickr authorization token is not valid anymore and a new one is required. From uploadr.out we have...
```
[uploadr] Checking if token is available... if not will authenticate
[uploadr] Getting new token.
https://www.flickr.com/services/oauth/authorize?oauth_token=YYYYYYYYYYY-XXXXXXXXXX&perms=delete
Verifier code (NNN-NNN-NNN): 
```
- To get a new toekn you have to first run the script at least one time manually in a ssh client to get an URL which you have to copy/paste in a browser... and once you get a return code provide it to the uploadr tool. You should be good to go.

Let me know if it works. 

oPromessa

**Comment by ze6killer** [comment]
Hello,

That seems to have solved it, thx!

Should I expect this to happen from time to time or is it most probably me who did something wrong?
(I know I tend to go into clicking frenzies where I don't know or care what I'm doing :)

Ze

**Comment by oPromessa** [comment]
I found it may happen from time to time... but it is not frequent... say once every 4˜5 months or so...
