### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by ziegwald** [oPromessa/flickr-uploader#5]
Hi, I got this following text when running uploadr.py

Traceback (most recent call last):
  File "./uploadr.py", line 235, in <module>
    TOKEN_CACHE = eval(config.get('Config', 'TOKEN_CACHE'))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'token_cache' in section: 'Config'

I don't know anything about coding so I don't know what was wrong.

**Comment by oPromessa** [comment]
Will check...

**Comment by oPromessa** [comment]
The template uploadr.ini file was wrong. Please load up the new uploadr.ini and reconfigure. You can use version 2.4.3 4eb1742 (on this link). Sorry!

**Comment by ziegwald** [comment]
Thanks, I'll try it tonight and see how it goes.

**Comment by oPromessa** [comment]
Bummer. I'm sorry about that!

### First things first:
- I have made further updates and included a small debug to check which python version your're using. Please test out  version is 2.5.5 (4b2e353).
- Before running uploadr.py make sure you run the command below:
  - To avoid running this command exerytime you log-in into your system, follow [the notes on this link](https://scipher.wordpress.com/2010/05/10/setting-your-pythonpath-environment-variable-linuxunixosx/) to edit file ~/.bashrc and place this command there.
   - Side note: will improve install instructions.
`$  export PYTHONPATH=~/apps/Python/lib/python2.7/site-packages
 $ ./uploadr.py -v `

### The Issue
- The issue has to do with a "simple" import of a module "xml" which seems to be failing or not the correct one on your system. Don't quite know the reason why. 
- Please rerun with version 2.5.5(4b2e353)  with and without the Workaround *mentioned below* and let me know the results, namely the python version you're using.

### Workaround
- Please edit *uploadr.ini* file and at the end, change LOGGING_LEVEL to 40 which is for uploadr.py to provide only ERROR and CRITICAL messages. As xml.etree is never called  40
`LOGGING_LEVEL = 40`
- To remove the workaround change it back to 30
`LOGGING_LEVEL = 30`

Sorry for this!

**Comment by oPromessa** [comment]
Sorry @ziegwald , yet another remark, if you can you should cleanup *all* your flickr photo (you can use organiser) and remove the local database file flickrdb just to make sure everything's cleaned up.
`$ rm flickrdb`

**Comment by ziegwald** [comment]
@oPromessa I've rerun the script (2.5.5) with and without the workaround but the error still stay the same. I'm using python 2.7.

**Comment by oPromessa** [comment]
- Version [2.5.6](https://github.com/oPromessa/flickr-uploader/tree/2.5.6) now available with fixes and improvements!

- Great news! Excellent you managed to find that out. Will put a line in the code for that so that people can uncomment it if they need it.

- I also use international (but western not eastern) characters and I had to force the following on the Task Scheduler... Although it states en_US with the utf8 added to it allows mine to work.
   - You could try with this setting...
   - or maybe try the Korean.UTF-8 setting: LANG=ko_KR.UTF-8 [Check out "Notes on UTF-8 and locales"](https://www.madboa.com/geek/utf8/)

```
export LC_ALL=en_US.utf8
export LANG=en_US.utf8
```

I will also attach an upload.cron file that I use for Task Scheduler.

Thanks!

**Comment by oPromessa** [comment]
- Version [2.5.7](https://github.com/oPromessa/flickr-uploader/tree/2.5.7) now available with fixes and improvements!

**Comment by oPromessa** [comment]
[V2.5.9 available](https://github.com/oPromessa/flickr-uploader/releases/tag/2.5.9)
- from my testing it is much better!

**Comment by oPromessa** [comment]
[V2.6.3 available](https://github.com/oPromessa/flickr-uploader/releases/tag/2.6.3)
