### ISSUE TITLE
Error message analysis

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#65]
Hello,

It's been some time since I wrote. I hadn't let the script run for some time.
2 weeks ago I downloaded the latest version, let it run, and here are my output files (hopefully stripped of any critical information.. maybe)
uploadr.cron calls: `python2.7 $FOLDER/uploadr.py -v -b -s -p 10 >>$FOLDER/uploadr.out 2>>$FOLDER/uploadr.err`

[uploadr.err.txt](https://github.com/oPromessa/flickr-uploader/files/1990612/uploadr.err.txt)
[uploadr.out.txt](https://github.com/oPromessa/flickr-uploader/files/1990613/uploadr.out.txt)

My questions are:
1) what should I understand from the last lines of uploadr.out, after "Completed uploading files", like "Error code: [3]" for instance?
2) what should I understand of the uploadr.err report? This is really gibberish to me, should I concern myself with it or is it rather some minor problems, which I reported more for development and optimization purposes?

Some comments:
1) out and err files were respectively 82MB and 697MB big.. so I removed some of them -> suggestion for some far distant future: check these file's size and delete the older info :)
2) at the beginning the script removes some sets from the DB (example: Men@Work) and adds them at the end again. Those are some Flickr sets which were created prior to my use of the script, so their pictures are not found on my NAS. Maybe there is some time to be gained by not removing them and adding them each time.

Take care
Ze

**Comment by oPromessa** [comment]
Hello there. Will come back to you over the weekend with a more complete answer.

 Meanwhile, the ERR file is more for me to track particular  execution errors.

To reduce size 1st of all you can of course  delete the files from time to time if there are no major errors. Secondly you can edit uploadr.ini .and set the variable logging level at the end of the file to a value like 40 to just report errors and critical situations. this will reduce drastically the size of the out and ERR files 

 Your suggestions are good so I’m log rotating. I am checking that. Some issues with  multi processing but I will look further.

Thanks

**Comment by ze6killer** [comment]
Hello,

Sure, no hurry.
Have a nice week-end :)

**Comment by oPromessa** [comment]
Hello @ze6killer, here are my comments to your topics:

### On your questions:
1. The specific "Error: 3: Photo already in set" indicates the app attempts to assign a pic to a set but it is already assigned to such set. This is then handled and the local DB is updated accordingly. No major worries here.
1. As you've suggested, uploadr.err is _"reported more for development and optimization purposes?"_

### On your comments:
1. Good suggestion. I'm working on it and will capture progress under issue #68
1. Yes, this is the current behaviour. At this time only takes a few seconds but will check in the future how feasible it is to make it. 

Thanks, oPromessa

**Comment by oPromessa** [comment]
#68 addressed on latest 2.8.5 release.
