### ISSUE TITLE
Deletion on Flickr Side

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#81]
Hello,

Sorry if you answered this before but I couldn't find it in the readme.

If I delete a file from Flickr, will it:
1. Stay on local but not be uploaded again (unless I do some specific things such as reset my database
2. Be uploaded again then next time the script launches
3. Be deleted from the matching local folder

I think it is option 1 but before trying I wanted to check with you.
Specifically, I have a video which is **_being processed_** for over a month now and I read on a forum that if this message lasts longer than 10min, one should simply delete and upload again.

Thx

PS: you wrote `flicr.com` in the readme

**Comment by oPromessa** [comment]
The answer is 1. 

The enhancement marked #67 would allow the behaviour you mention under 2. Still under review...

PS: Ooops. I'll fix it

**Comment by ze6killer** [comment]
Sounds good to me for now, I just wanted to make sure that it wouldn't be 3 :)
