### ISSUE TITLE
What does it means this Error

### ISSUE THREAD

**Issue by emmtte** [oPromessa/flickr-uploader#84]
I have this ERROR but uploaded work
``[2111][2018.10.16 15:43:40]:[MainProcess][ERROR   ]:[root] After CYCLE Up/Reuploading:[0/10 attempts].
``
What does it's mean?

**Comment by oPromessa** [comment]
Hello @ManuCart,

* It's not actually an ERROR. It's a WARNING in fact. I'm fixing that for future versions. 
* It tells us on which upload attempt are we at. In this case "0/10" (first attempt) which is ok! If an error actually occurred, it would be reported on the following messages.

Let me know if you have any more difficulties.
