### ISSUE TITLE
This is an issue for me: Flickr changes for free accounts

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#89]
Hey, I've wanted to write to you ever since Flickr made its anouncement. Sorry if this isn't the right place, I never found a way to PM you :>

So, with the disappearance of the free Flickr account as we know it, I'll have to find some other way to secure my pictures. I am not willing to pay for the flickr pro at this point, for the price I'd rather go with dropbox or google, who provide some efficient syncing clients rather than with Flickr who lets its users do the work themselves.
Actually I think I'll just buy an external drive, back my NAS on it once in a while and store this drive outside of my house...

This doesn't solve the issue about "how am I gonna share the pictures with my family now?" , although it might be the time for me to go and test synology's photo station.
Also my new source of worry is the bit-rot, which makes me nervous some of my pics won't be accessible the next time I checked.

Anyways, I wanted to thank you once again for your good work and your openness to suggestions.
I hope that I was able to help you at least a little bit with my testing and comments.

Take Care

Ze

**Comment by oPromessa** [comment]
Thank you for your encouragement @ze6killer!! Really appreciated. Your input throughout these past few months were great. Yes, sad news from Flickr. 

1. If you happen to be an Amazon Prime user, you can use Synology Cloud Sync to upload all your pics (no limits for pics) to Amazon Drive and use the Amazon Photos apps to view them. Videos are limited to 5GB storage.
   * Creation of Albums is not possible... it's manual! I'm looking into their API for a possible port of this tool into Amazon (don't know if I'll have the time)!

1. For local backup, [make sure you use a compatible USB Disk](https://www.synology.com/en-global/compatibility?search_by=category&category=usb_3_0_storage_devices&p=1) as I had a few problems with non-compatible disks. 

1. I use Photo Station (did not move into Moments... still see some issues there) and somehow works okay. Although I don't make a lot of sharing with Photo Station!

Let's keep in touch!

**Comment by ze6killer** [comment]
Happy New Year.

I wanted to let you know that if you ever needed someone to test some other scripts you can just drop me a line and I'll get a notification by mail. I'll be glad to help as always :)

Since someone in my family has amazon prime, I'll give it a try. Althout the hardrive worked fine, I find that the synology mobile app is not as convenient as Flickr was to access photos quickly.. who knows, maybe I'll go for a paid account in the end :)

C ya
